apiVersion: v1
kind: Service
metadata:
  name: smart-maintenance-backend-service
  namespace: default
  labels:
    app: smart-maintenance-backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: smart-maintenance-backend
---
apiVersion: v1
kind: Service
metadata:
  name: smart-maintenance-backend-nodeport
  namespace: default
  labels:
    app: smart-maintenance-backend
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30800
    protocol: TCP
    name: http
  selector:
    app: smart-maintenance-backend
