"""add_maintenance_logs_table

Revision ID: 2a6b3cf9a7fc
Revises: d4a01b4dd5a1
Create Date: 2025-06-09 10:54:30.018560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a6b3cf9a7fc'
down_revision: Union[str, None] = 'd4a01b4dd5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.String(length=255), nullable=False),
    sa.Column('completion_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('technician_id', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'PARTIALLY_COMPLETED', 'FAILED', 'CANCELLED', name='maintenancetaskstatus'), nullable=False),
    sa.Column('actual_duration_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_logs_equipment_id'), 'maintenance_logs', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_id'), 'maintenance_logs', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_task_id'), 'maintenance_logs', ['task_id'], unique=False)
    op.drop_index(op.f('ix_sensor_readings_sensor_id_timestamp_desc'), table_name='sensor_readings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sensor_readings_sensor_id_timestamp_desc'), 'sensor_readings', ['sensor_id', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index(op.f('ix_maintenance_logs_task_id'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_id'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_equipment_id'), table_name='maintenance_logs')
    op.drop_table('maintenance_logs')
    # ### end Alembic commands ###
