"""add human_decisions table (minimal)

Revision ID: 7bbe1dbdb5f5
Revises: 71994744cf8e
Create Date: 2025-09-26 23:16:17.984709 (trimmed to minimal operations)

This migration was autogenerated with substantial unrelated schema drops due to
historical drift between the live database and Alembic's notion of the model state.
All unrelated destructive operations have been removed; only the creation of the
human_decisions table and its supporting indexes remain.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7bbe1dbdb5f5"
down_revision: Union[str, None] = "71994744cf8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:  # pragma: no cover
    op.create_table(
        "human_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.String(length=255), nullable=False),
        sa.Column("operator_id", sa.String(length=255), nullable=False),
        sa.Column("decision", sa.String(length=100), nullable=False),
        sa.Column("justification", sa.Text(), nullable=True),
        sa.Column("additional_notes", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("correlation_id", sa.String(length=255), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_human_decisions_correlation_id", "human_decisions", ["correlation_id"], unique=False)
    op.create_index("ix_human_decisions_operator_id", "human_decisions", ["operator_id"], unique=False)
    op.create_index("ix_human_decisions_request_id", "human_decisions", ["request_id"], unique=False)


def downgrade() -> None:  # pragma: no cover
    op.drop_index("ix_human_decisions_request_id", table_name="human_decisions")
    op.drop_index("ix_human_decisions_operator_id", table_name="human_decisions")
    op.drop_index("ix_human_decisions_correlation_id", table_name="human_decisions")
    op.drop_table("human_decisions")
